### ISSUE TITLE
Add socket route to check for the helper

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/BlueBubbles-Server#161]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#requests`.

**Comment by CSab6482** [comment]
Can this also send a message to the Android app along the lines of "Hey it looks like you have the helper on your computer! Be sure to enable the private API toggle!" Or just have it enabled by default if it detects the helper? I reinstalled the app and I couldn't send read receipts because I forgot it was a toggle

**Comment by zlshames** [comment]
This is now part of the server metadata
