### ISSUE TITLE
Not working on macOS Bigsur

### ISSUE THREAD

**Issue by AbedYamout** [BlueBubblesApp/BlueBubbles-Server#200]
The Server Apps shows notification that the server can't work on macOS Bigsur because of an API Limitation. also everytime i login to the imessage app in mac it crashes, i will try macOS Catalina will that work?

**Comment by romhacks** [comment]
Only new chat creation doesn't work on big sur. Once you make a chat, it will work correctly, this is a known issue because of changes Apple made. The iMessage crash is likely not related to BlueBubbles, if it's possible for you to try Catalina, I would. I'd recommend you close this issue and join the BlueBubbles discord server so you can get faster support. https://discord.gg/yC4wr38
