### ISSUE TITLE
add a way for the server to accept an error response for a given transaction from the private api

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#326]
inside the private API we often perform checks before completing actions, such as if a chat exists before sending a message to it. When these checks don't pass, we don't send any data back to the server so a REST API request appears to never complete, which is incorrect. We should send an error response back instead

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@tneot01` in `#server-development`.

**Comment by zlshames** [comment]
i found the underlying issue and have fixed it i believe. The issue was 2 fold. First, the ErrorMiddleware wasn't even used. Not sure how that happened. I checked git blame but it just showed me adding the Metrics Middleware, not removing anything related the the Error Middleware, which wasn't even being used. The second issue was the metrics middleware was wrapped in a try/catch making it catch any errors that the ErrorMiddleware was _supposed_ to catch

**Comment by zlshames** [comment]
Fixed, branch: `zach/326/transaction-error-support`. Just return an `error` key at the same level as `transactionId` and `data`
