### ISSUE TITLE
Possible to detect local setting instead of Ngrok URL?

### ISSUE THREAD

**Issue by wilsoncliu** [BlueBubblesApp/bluebubbles-server#390]
Was wondering if it's possible for the bluebubbles app to detect when the Mac server is local instead of using the Ngrok link which would possibly make it faster locally?

**Comment by tneotia** [comment]
To clarify here, basically server detects that connected client(s) are on the same local network, and updates itself to use the local IP as the URL rather than ngrok (removing the middle man).

Another thing that might work is to make server accessible over ngrok and local IP at the same time

**Comment by wilsoncliu** [comment]
> To clarify here, basically server detects that connected client(s) are on the same local network, and updates itself to use the local IP as the URL rather than ngrok (removing the middle man).
> 
> Another thing that might work is to make server accessible over ngrok and local IP at the same time

thank you, you said it much better!

**Comment by zlshames** [comment]
@tneotia i think this would be a client issue, not a server issue. What he wants is to be able to have the app "scan" the local network for devices that could have BB running on it. To do that, you'll probably need to do something like the following:

https://stackoverflow.com/questions/67835616/flutter-dart-scan-local-network-to-get-ip-and-hostname-of-connected-devices

And check and see if they respond to requests on the default port (1234). If they do, then it's possible to connect. Once connected, it'll update with the ngrok URL from firebase since it would be difference from the localhost one it originally finds. It'll just need the user to type the password to connect, not the URL.
