### ISSUE TITLE
refresh cloudflare when INF message occurs

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#394]
https://github.com/cloudflare/cloudflared/issues/306#issuecomment-1197946155

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@zach` in `#server-support`.

**Comment by zlshames** [comment]
Cloudflare has a retry limit that is set to 5 by default. Each time it needs to retry, it waits for 1, 2, 4, 8, and 16 seconds. With 16 seconds being waited on for the 5th retry. I have configured the server to manually restart the proxy service is the 16 second threshold is hit. I've also removed the refresh timer for cloudflare since it seems there is no expiration. It will also help with DNS caching after the first connection since the URL theoretically wont change unless an error is detected.

**Comment by zlshames** [comment]
Code for my changes is on the `development` branch
