### ISSUE TITLE
Cannot add a tapback to audio messages

### ISSUE THREAD

**Issue by cynical89** [BlueBubblesApp/bluebubbles-server#462]
_No content_

>  Issue created by BlueBubbles Bot in the `BlueBubbles` commnity on behalf of `@CSab6482` in `#android-support`.

**Comment by digisavvy** [comment]
I, too, am experiencing this issue.

Bluebubbles server 1.4.1, on Mac OS 13.01

Tap backs has been working when running bluebubbles on my MacBook which was running 12.x. I moved bluebubbles to my mac mini and it was running 13.01 and I noticed that tapbacks don't work any longer.

**Comment by digisavvy** [comment]
@tneotia - thanks for the speedy reply. That worked for me. Since my m1 is relatively new I had to:
1. Install xcode dev tools for using Git commands
2. Had to download Xcode from App Store to run the Xcode project
3. I had to add an apple ID to xcode to successfully build the bundle release.

A couple of items to add to the docs. Thank you!

**Comment by tneotia** [comment]
Typically you shouldn't need to build the bundle yourself, the releases in the repository are indicative of the latest stable code. Glad it's working though!
