### ISSUE TITLE
Google sign in not compatible with Googles secure browser policy

### ISSUE THREAD

**Issue by samir-a-ali** [BlueBubblesApp/bluebubbles-server#542]
![image0](https://github.com/BlueBubblesApp/bluebubbles-server/assets/107290291/7e393d36-35ec-4ef7-9cee-d8657104fdbb)

Error 403: disallowed_useragent
Request details: access_type=online login_hint=________579@gmail.com hl=en-US android=1 response_type=consent_proof android_options=CAMQAQ client_id=_________-qrpbpjj1mgp248kt33kj75or771gpk4r.apps.googleusercontent.com scope=https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/cloud-platform openid https://www.googleapis.com/auth/userinfo.profile

**Comment by zlshames** [comment]
Yeah, this is known. it's because our "app" is not validated by Google. Mainly because Google says we are using "3-pronged" scope permissions which give too wide of a breadth of permissions. Which is true. However, we don't have a great way to move forward with it, which worries us as to how we are going to proceed forward with Google Sign in. There aren't scopes we can use to lessen our access scope (for what we need to do).

Google advised us to create a Service Account with _less_ permissions. However, that would require users to manually add that Services account to their Google Cloud account. So it would require user-intervention, which is what we are trying to avoid all together.

Either way, we are struggling to figure out how to move forward here. Maybe we can figure something out...

**Comment by zlshames** [comment]
Fixed & verified by Google now :) (next server/client update)
