### ISSUE TITLE
Fix 403 Google authentication

### ISSUE THREAD

**Issue by zlshames** [BlueBubblesApp/bluebubbles-server#568]
Might be happening because the call to add firebase to the GCP fails. Unsure why it's failing though. 

Also discovered that manually enabling the firebase API may not auto create the service account required. But using the API may automatically do it. We have to make sure that no matter if it's enabled manually or automatically, the service account gets created

**Comment by Rihcus** [comment]
![Screen Shot 2023-09-20 at 11 44 05 AM](https://github.com/BlueBubblesApp/bluebubbles-server/assets/30292597/0fdbbf87-46b1-4b5e-b05c-0daf0dc3462e)

**Comment by zlshames** [comment]
> ![Screen Shot 2023-09-20 at 11 44 05 AM](https://user-images.githubusercontent.com/30292597/269342882-0fdbbf87-46b1-4b5e-b05c-0daf0dc3462e.png)

This issue was fixed in our 1.8.0 release

**Comment by KNIX3** [comment]
Is there a temporary solution for this issue? I have never used blue bubbles before and am stuck with the 403 error trying to set it up. Some quick searching suggests there used to only be a manual way to set up Firebase. Since the new automatic way is simply broken for me, how might I do it manually? Was it removed from the docs with the last couple of releases?

**Comment by jjoelj** [comment]
For people encountering this issue, a temporary solution is to log in to https://console.firebase.google.com/

Once you do that, the automatic project creation will work.

**Comment by zlshames** [comment]
Closing as it's fixed next update
